"use client";
import { useState } from "react";
import type { AiSource, Task } from "@/lib/types";
import { apiSummary } from "@/lib/api";

export default function SummaryPanel({ tasks }: { tasks: Task[] }) {
  const [text, setText] = useState<string | null>(null);
  const [source, setSource] = useState<AiSource | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const done = tasks.filter((t) => t.done).length;
  const pct = tasks.length ? Math.round((done / tasks.length) * 100) : 0;

  const run = async () => {
    setBusy(true);
    setError(null);
    try {
      const r = await apiSummary(tasks);
      setText(r.summary);
      setSource(r.source);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed");
    } finally {
      setBusy(false);
    }
  };

  return (
    <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
      <div className="flex items-center justify-between">
        <h2 className="font-semibold">Progress</h2>
        <span className="text-sm text-slate-500">{done}/{tasks.length} done</span>
      </div>
      <div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100" role="progressbar" aria-valuenow={pct} aria-valuemin={0} aria-valuemax={100}>
        <div className="h-full bg-indigo-600 transition-all" style={{ width: `${pct}%` }} />
      </div>
      <button onClick={() => void run()} disabled={busy} className="mt-3 rounded-lg bg-indigo-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-indigo-500 disabled:opacity-50">
        {busy ? "Summarizing…" : "✨ Generate AI summary"}
      </button>
      {error && <p className="mt-2 text-sm text-red-600">{error}</p>}
      {text && (
        <div className="mt-3 rounded-lg bg-indigo-50 p-3 text-sm text-slate-800">
          <p>{text}</p>
          <p className="mt-1 text-xs text-slate-500">{source === "llm" ? "Generated by GitHub Models LLM" : "Generated by built-in heuristics (set GITHUB_TOKEN for LLM)"}</p>
        </div>
      )}
    </section>
  );
}
